### ISSUE TITLE
[12장 699p] MyEnum 클래스의 compareTo()

### ISSUE THREAD

**Issue by choigy1001** [Study-Standard-Of-Java/community#18]
여기서 제네릭을 통해 간단히 작성할 수 있었다고 하는데 왜 그런지 다같이
생각해보면 좋겠습니다!

**Comment by choigy1001** [comment]
고민을 해봤는데 단순히 
제한없이 MyEnum<T>를 한다면 타입에 enum이 오지 않아 ordinal 정의되어 있는지 알 수 없다는 의미인거 같네요!

**Comment by kiiiyeon** [comment]
근영님 말씀이 맞는 것 같네요 책 다시 읽어보니까
> compareTo()를 위와 같이 간단히 작성할 수 없었을 것이다. 타입 T에 ordinal()이 정의되어 있는지 확인할 수 없기 때문이다.

라고 적혀있네요. Enum에서만 ordinal()을 사용할 수 있는데 Enum이 타입매개변수로 들어오지 않을 수도 있어서 인듯 합니다!
