### ISSUE TITLE
[12장 712p] 컴파일러를 직접 작성하지 않는 이상 SOURCE 유지 정책은 필요없다?

### ISSUE THREAD

**Issue by choigy1001** [Study-Standard-Of-Java/community#19]
`@Retention ` 의 유지 정책중 하나인 SOURCE 가
컴파일러를 직접 작성할 것이 아니면 , 이 유지 정책이 필요하지 않다고 말했습니다.
여기에 대해서 생각해보고 의견 나누면 좋겠습니다~

**Comment by kiiiyeon** [comment]
SOURCE 정책은 컴파일 할 때만 사용하고 사라지는데 애노테이션의 메모리를 버린다고 하네요! 컴파일러를 직접 작성하지 않는 이상 주석처럼 사용된다고 합니다 ~

출처: https://codingrepo.tistory.com/41
백기선 라이브 스터디 강의에서 나온 말 같아요 ~
