### ISSUE TITLE
[7장] 인터페이스와 추상 클래스 차이

### ISSUE THREAD

**Issue by choigy1001** [Study-Standard-Of-Java/community#8]
추상클래스와 인터페이스를 봤을때 어떻게 보면 차이가 없어 보입니다.
각자 공부하면서 어떻게 차이를 이해했는지 공유해보면 좋겠습니다~

**Comment by cpprhtn** [comment]
#### 추상 클래스
관련성이 높은 클래스 간에 코드를 공유하고 싶은 경우
추상 클래스를 상속 받을 클래스들이 공통으로 가지는 메소드와 필드가 많거나, public이외의 접근자 선언이 필요한 경우
각 인스턴스에서 상태 변경을 위한 메소드가 필요한 경우

#### 인터페이스
서로 관련성이 없는 클래스들이 인터페이스를 구현하게 되는 경우
특정 데이터 타입의 행동을 명시하고 싶은데, 어디서 그 행동이 구현되는지는 신경쓰지 않는 경우
다중상속을 허용하고 싶은 경우

#### 생각한 느낌
추상클래스는 자신의 기능들을 하위 클래스로 확장시키는 느낌이고, 인터페이스는 인터페이스에 정의된 메소드들을 각 클래스의 목적에 맞도록 기능을 구현하는 느낌인 것 같습니다.

**Comment by KoEunseong** [comment]
추상클래스 : 추상메서드를 선언하여 클래스로서 자손클래스에서 완성을 유도, 일반 메서드들 사용 가능
인터페이스 : 오직 추상메서드와 상수만을 멤버로 가진다. 클래스와 달리 "다중 상속"이 가능

-사용
1) 인터페이스의 경우 다중상속이 가능하기 때문에 다른 조상클래스를 상속하지만 공통된 기능을 부여하고 싶을 때 사용한다.
ex) tank와 dropship은 각자 GroundedUnit, AirUnit으로 조상클래스가 다르지만 인터페이스 Repairable을 각자
구현해서 둘다 리페어가 가능하다.
2) 추상클래스는 일반 클래스와 비슷하게 생각하는데 추상메서드를 선언을 해서 조상과 자손이 같은 기능이 필요할 때 자손이 기능을 다시 구현하도록 한다.
(어려워서 맞는 지 잘 모르겠네요 ㅠㅠ)

**Comment by choigy1001** [comment]
확인했습니다~ 
다들 잘 이해하신거 같아서 좋네요 :)
